# Generated by Django 6.1 on 2026-08-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_is_admin_customuser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='action_id',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='resource_id',
            new_name='resource',
        ),
    ]
